local lLex = require("utils.lua_lex")
lLex:load("utils/json_lex.lua")
-- debug.sethook(function(a, b)
--     print(a, b)
-- end, "l", 0)
xpcall(lLex.test, function(a)
    print("\n")
    print(a)
    print(lLex.linenumber)
    print(lLex.position)
end, lLex)
